### ISSUE TITLE
Light turns on but Amazon Echo says device is not connected

### ISSUE THREAD

**Issue by J0nnyMak0** [mjg59/ulfire#1]
I'm using your script with Wemo Link and Amazon Echo. This is by far the best solution I've found. Thanks for this!

However...

From time to time, after I run the script and ask Amazon Echo to turn on the light, the light turns on, but Echo says it was not able to find the light. At that point, if I try to turn on any other Wemo Link connected light, the first light that already turned on turns off and all Wemo Link lights become unavailable.

**Comment by mjg59** [comment]
Hm. What firmware version are you running on your Link? If you run ulfire with the -d argument, do you see it still receiving commands from the Echo? When you say "all Wemo Link lights become unavailable", do you mean that the Wemo app is also unable to see them?

**Comment by J0nnyMak0** [comment]
I'll check the firmware version when I'm home (currently travelling, and wemo app not on my phone). I did however notice that the problem I reported happens soon after I've run the script. Once I give it some time (5-10 minutes) then everything works as expected. I'll update you when I can get to my computer and phone and answer your questions.

**Comment by J0nnyMak0** [comment]
Link firmware:
WeMo_WW_2.00.9268.PVT-OWRT-Link

This is what I see in the script output (run with -d option) for a successful command to Echo:

Responding to description.xml for Fauxhue
Responding to description.xml for Fauxhue
Responding to search for Fauxhue
Responding to search for Fauxhue

This is what I see for failed commands:
Responding to search for Fauxhue
Responding to search for Fauxhue
Responding to search for Fauxhue
Responding to search for Fauxhue
Responding to search for Fauxhue

The WeMo app from my phone is sill able to control devices even when echo is having intermittent problems.

So far as I can tell, this only happens either when 

a. I have just started the script
b. after long periods of inactivity

In both cases just giving it some time seems to resolve the problem.

If I were to make a complete wild @$$ guess, I would say it sounds like some timeout issue.

Let me know if you need more info/testing.

**Comment by mjg59** [comment]
Just after you've started the script is probably a lag due to the Echo's periodic rescanning for devices - ulfire doesn't currently ensure it uses the same UUID, so it may change internal address when you restart it. Clicking "Discover devices" again from the Alexa UI should fix that. The latter is strange - I'll post a version that has more debug output and we can see whether there's more going on. Is there any chance that the device you're running Ulfire on is changing IP address?

**Comment by J0nnyMak0** [comment]
As far as I can tell my router is not changing the ip for the wemo link. Also in my last report I got it backwards. An _unsuccessful_ command results in:

Responding to description.xml for Fauxhue
Responding to description.xml for Fauxhue

**Comment by J0nnyMak0** [comment]
Seems to be working alright after an initial startup delay. I think that is quite acceptable. Closing.
